#!/usr/bin/env python3
"""
midi_to_arduino.py — Convert a MIDI file into an Arduino Note array.

Install deps:  pip install mido
Usage:         python midi_to_arduino.py song.mid [track_index]
Output:        song_notes.h  — drop this file into your Arduino sketch folder,
               then #include "song_notes.h" in motor_music.ino

If no track_index is given, the track with the most notes is auto-selected.
When multiple notes play simultaneously (chords), the highest pitch is kept
so the melody line is preserved.
"""

import sys
import os
import mido

# ── MIDI note number → name string ────────────────────────────────────────
NOTE_NAMES = ["C", "CS", "D", "DS", "E", "F", "FS", "G", "GS", "A", "AS", "B"]

def note_name(midi_note):
    octave = (midi_note // 12) - 1
    name   = NOTE_NAMES[midi_note % 12]
    return f"{name}{octave}"           # e.g. "A4", "CS5"

def note_to_freq(midi_note):
    return round(440.0 * 2 ** ((midi_note - 69) / 12.0))

# ── Tempo map: handles tempo changes mid-song ──────────────────────────────
def build_tempo_map(mid):
    """Returns sorted list of (abs_tick, tempo_us_per_beat)."""
    tempo_map = [(0, 500000)]   # default = 120 BPM
    for track in mid.tracks:
        abs_tick = 0
        for msg in track:
            abs_tick += msg.time
            if msg.type == "set_tempo":
                tempo_map.append((abs_tick, msg.tempo))
    tempo_map.sort()
    return tempo_map

def ticks_to_ms(start_tick, end_tick, tempo_map, tpb):
    """Convert a tick range to milliseconds, respecting tempo changes."""
    total_us = 0.0
    for i, (t_tick, tempo) in enumerate(tempo_map):
        seg_start = max(t_tick, start_tick)
        seg_end   = end_tick if i == len(tempo_map) - 1 else min(end_tick, tempo_map[i + 1][0])
        if seg_end <= seg_start:
            continue
        total_us += (seg_end - seg_start) * tempo / tpb
    return round(total_us / 1000)

# ── Extract monophonic note list from one track ────────────────────────────
def extract_notes(mid, track_idx):
    tempo_map = build_tempo_map(mid)
    tpb       = mid.ticks_per_beat
    track     = mid.tracks[track_idx]

    # Build absolute-tick events
    events = []
    abs_tick = 0
    for msg in track:
        abs_tick += msg.time
        if msg.type in ("note_on", "note_off"):
            on = (msg.type == "note_on" and msg.velocity > 0)
            events.append((abs_tick, msg.note, on))

    # Pair note_on with note_off → (start_tick, end_tick, midi_note)
    active   = {}   # midi_note -> start_tick
    segments = []
    for tick, note, on in events:
        if on:
            active[note] = tick
        elif note in active:
            segments.append((active.pop(note), tick, note))

    segments.sort()

    # When notes overlap (chord / polyphony), keep highest pitch per time slot
    merged = []
    for start, end, note in segments:
        if merged and start < merged[-1][1]:           # overlap with previous
            if note > merged[-1][2]:                   # higher pitch wins
                merged[-1] = (merged[-1][0], end, note)
        else:
            merged.append([start, end, note])

    # Build result list, inserting REST for gaps
    result = []
    cursor = 0
    for start, end, note_num in merged:
        if start > cursor:
            rest_ms = ticks_to_ms(cursor, start, tempo_map, tpb)
            if rest_ms >= 20:                          # ignore tiny gaps
                result.append((0, rest_ms, "REST"))
        dur_ms = ticks_to_ms(start, end, tempo_map, tpb)
        if dur_ms > 0:
            result.append((note_to_freq(note_num), dur_ms, note_name(note_num)))
        cursor = end

    return result

# ── Output helpers ─────────────────────────────────────────────────────────
def to_camel(path):
    base  = os.path.splitext(os.path.basename(path))[0]
    # Replace anything that isn't a letter or digit with underscore
    import re
    base  = re.sub(r"[^a-zA-Z0-9]+", "_", base).strip("_")
    parts = [p for p in base.split("_") if p]
    return parts[0].lower() + "".join(p.capitalize() for p in parts[1:])

def generate_header(notes, array_name):
    guard = array_name.upper() + "_H"
    lines = []
    lines.append(f"// {array_name} — generated by midi_to_arduino.py")
    lines.append(f"// {len(notes)} notes")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"const Note {array_name}[] PROGMEM = {{")

    row = []
    for freq, dur, label in notes:
        tag = "REST" if freq == 0 else str(freq)
        row.append(f"{{{tag},{dur}}}")
        if len(row) == 6:
            lines.append("  " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ",".join(row) + ",")

    lines.append("};")
    lines.append(f"const int LEN_{array_name.upper()} = sizeof({array_name}) / sizeof({array_name}[0]);")
    lines.append("")
    lines.append(f"#endif // {guard}")
    return "\n".join(lines)

# ── Main ───────────────────────────────────────────────────────────────────
def main():
    if len(sys.argv) < 2:
        print("Usage: python midi_to_arduino.py <file.mid> [track_index]")
        sys.exit(1)

    midi_path = sys.argv[1]
    if not os.path.exists(midi_path):
        print(f"File not found: {midi_path}")
        sys.exit(1)

    mid = mido.MidiFile(midi_path)

    print(f"\nFile : {os.path.basename(midi_path)}")
    print(f"Type : {mid.type}   TPB: {mid.ticks_per_beat}")
    print(f"\nTracks:")
    for i, t in enumerate(mid.tracks):
        n = sum(1 for m in t if m.type == "note_on" and m.velocity > 0)
        print(f"  [{i}] {t.name!r:35s}  {n:4d} note-ons")

    if len(sys.argv) > 2:
        track_idx = int(sys.argv[2])
    else:
        track_idx = max(
            range(len(mid.tracks)),
            key=lambda i: sum(1 for m in mid.tracks[i] if m.type == "note_on" and m.velocity > 0)
        )
        print(f"\nAuto-selected track [{track_idx}]: {mid.tracks[track_idx].name!r}")
        print("  (pass a track number as 2nd argument to override)\n")

    notes = extract_notes(mid, track_idx)

    array_name = to_camel(midi_path)
    header     = generate_header(notes, array_name)

    out_path = os.path.splitext(midi_path)[0] + "_notes.h"
    with open(out_path, "w") as f:
        f.write(header)

    print(f"Generated {len(notes)} notes  →  {out_path}")
    print(f"\nFirst 10 entries:")
    for freq, dur, label in notes[:10]:
        print(f"  {label:6s}  {freq:5} Hz   {dur} ms")

    print(f"""
── How to use ──────────────────────────────────────────────────────────────
1. Copy {os.path.basename(out_path)} into your Arduino sketch folder.
2. In motor_music.ino, add at the top (after the note #defines):
     #include "{os.path.basename(out_path)}"
3. Add to the SongId enum:
     SONG_{array_name.upper()},
4. Add to the switch in loop():
     case SONG_{array_name.upper()}:
       playSong({array_name}, LEN_{array_name.upper()});
       break;
5. Set:
     const SongId ACTIVE_SONG = SONG_{array_name.upper()};
────────────────────────────────────────────────────────────────────────────
""")

if __name__ == "__main__":
    main()
